version: '3.8'

services:
  backendassignment.web:
    build:
      context: .
      dockerfile: src/BackendAssignment.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqliteConnection=Data Source=/app/data/database.sqlite
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - backendassignment-network

networks:
  backendassignment-network:
    driver: bridge

volumes:
  sqlserver-data:
